### PR TITLE
added possibility to disable the timer(s)

### PR DESCRIPTION
**Pull request by bubenkoff**
This change is [Reviewable](https://reviewable.io/reviews/thebarty/exit-intent/1)

### CODE REVIEW

**Comment by bubenkoff** [comment]
@thebarty thanks, can you please make a new release?

**Comment by thebarty** [comment]
@bubenkoff just added as collaborator on this project. Can you take care of the release? I am really busy right now and would love to get your help on it

**Comment by bubenkoff** [comment]
@thebarty, but I don't have the permissions to npm to release
it's the same username as on github

**Comment by thebarty** [comment]
@bubenkoff Just added you to as npm owner. Great to have you in the team!

**Pull request merged**
